name: BaseHider
version: '0.1.6'
main: io.github.chanemilia.baseHider.BaseHider
api-version: '1.21'
authors: [ChanEmilia]
description: Hides underground caves and bases using PacketEvents packets.

commands:
  basehider:
    description: Reload the configuration
    permission: basehider.op
    usage: /basehider reload